export {default as Hero} from './Hero'
export {default as BlogContent} from './BlogContent'
export {default as Location} from './Location'
export {default as Statistics} from './Statistics'
export {default as Steps} from './Steps'