import './globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

//import components
import {Navbar, Footer, UpperNavbar} from '@/components';

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <UpperNavbar/>
      <Navbar/>
      {children}
      <Footer /></body>
    </html>
  )
}
